### ISSUE TITLE
vibe.core.process.pipe cannot call @system function core.stdc.stdio._handleToFD!()._handleToFD

### ISSUE THREAD

**Issue by SingingBush** [vibe-d/vibe-core#282]
On Windows build with dmd 2.094 to 2.096 I'm seeing these errors with vibe-core 1.18.0:

```
vibe-core 1.18.0: building configuration "winapi"...
C:\Users\runneradmin\AppData\Local\dub\packages\vibe-core-1.18.0\vibe-core\source\vibe\core\process.d(608,28): Error: `@safe` function `vibe.core.process.pipe` cannot call `@system` function `core.stdc.stdio._handleToFD!()._handleToFD`
C:\hostedtoolcache\windows\dc\dmd-2.096.1\x64\dmd2\windows\bin\..\..\src\druntime\import\core\stdc\stdio.d(1823,9):        `core.stdc.stdio._handleToFD!()._handleToFD` is declared here
C:\Users\runneradmin\AppData\Local\dub\packages\vibe-core-1.18.0\vibe-core\source\vibe\core\process.d(609,29): Error: `@safe` function `vibe.core.process.pipe` cannot call `@system` function `core.stdc.stdio._handleToFD!()._handleToFD`
C:\hostedtoolcache\windows\dc\dmd-2.096.1\x64\dmd2\windows\bin\..\..\src\druntime\import\core\stdc\stdio.d(1823,9):        `core.stdc.stdio._handleToFD!()._handleToFD` is declared here
C:\hostedtoolcache\windows\dc\dmd-2.096.1\x64\dmd2\windows\bin\dmd.exe failed with exit code 1.
Error: Process completed with exit code 1.
```

**Comment by SingingBush** [comment]
worth noting that this is with all dmd versions since 2.094 and also affects vibe-core 1.22.0:

```
C:\Users\runneradmin\AppData\Local\dub\packages\vibe-core-1.22.0\vibe-core\source\vibe\core\process.d(608,28): Error: `@safe` function `vibe.core.process.pipe` cannot call `@system` function `core.stdc.stdio._handleToFD!()._handleToFD`
C:\hostedtoolcache\windows\dc\dmd-2.098.1\x64\dmd2\windows\bin64\..\..\src\druntime\import\core\stdc\stdio.d(1876,9):        `core.stdc.stdio._handleToFD!()._handleToFD` is declared here
C:\Users\runneradmin\AppData\Local\dub\packages\vibe-core-1.22.0\vibe-core\source\vibe\core\process.d(609,29): Error: `@safe` function `vibe.core.process.pipe` cannot call `@system` function `core.stdc.stdio._handleToFD!()._handleToFD`
C:\hostedtoolcache\windows\dc\dmd-2.098.1\x64\dmd2\windows\bin64\..\..\src\druntime\import\core\stdc\stdio.d(1876,9):        `core.stdc.stdio._handleToFD!()._handleToFD` is declared here
C:\hostedtoolcache\windows\dc\dmd-2.098.1\x64\dmd2\windows\bin64\dmd.exe failed with exit code 1.
```

**Comment by SingingBush** [comment]
This problem remains on vibe-core 1.22.4 see example build log: https://github.com/buggins/ddbc/runs/6684795912?check_suite_focus=true

```
taggedalgebraic 0.11.22: building configuration "library"...
eventcore 0.9.20: building configuration "winapi"...
stdx-allocator 2.77.5: building configuration "library"...
vibe-core 1.22.4: building configuration "winapi"...
C:\Users\runneradmin\AppData\Local\dub\packages\vibe-core-1.22.4\vibe-core\source\vibe\core\process.d(608,28): Error: `@safe` function `vibe.core.process.pipe` cannot call `@system` function `core.stdc.stdio._handleToFD!()._handleToFD`
C:\hostedtoolcache\windows\dc\dmd-2.098.1\x64\dmd2\windows\bin64\..\..\src\druntime\import\core\stdc\stdio.d(1876,9):        `core.stdc.stdio._handleToFD!()._handleToFD` is declared here
C:\Users\runneradmin\AppData\Local\dub\packages\vibe-core-1.22.4\vibe-core\source\vibe\core\process.d(609,29): Error: `@safe` function `vibe.core.process.pipe` cannot call `@system` function `core.stdc.stdio._handleToFD!()._handleToFD`
C:\hostedtoolcache\windows\dc\dmd-2.098.1\x64\dmd2\windows\bin64\..\..\src\druntime\import\core\stdc\stdio.d(1876,9):        `core.stdc.stdio._handleToFD!()._handleToFD` is declared here
C:\hostedtoolcache\windows\dc\dmd-2.098.1\x64\dmd2\windows\bin64\dmd.exe failed with exit code 1.
Error: Process completed with exit code 1.
```

**Comment by s-ludwig** [comment]
Should be fixed by #330 (0f17a2f7d8290faf762a3743784221143ec74741)
